### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by tentacleuno** [TwidereProject/TwidereProject.github.io#5]
I was planning on fixing a typo on [your website](https://twidere.com), but I'm left wondering where the source code actually is.

Both this repository and the one under the DimensionDev org do not contain the source code for the Twidere website. Despite the fact that they are linked from the Twidere website, they are React applications, whereas your website relies upon GitHub Pages (statically generated).

Can you please provide me with the link to your website? I'd still like to fix that typo 🙂

**Comment by Tlaster** [comment]
It's [here](https://github.com/DimensionDev/Twidere-Website/tree/gh-pages), under the `gh-pages` branch.
And we're building a new site for the Twidere X now so the react project you just saw are the new site.

**Comment by tentacleuno** [comment]
Thanks.
